x = input()
print(f'{x}{x}{x}{x}{x}{x}{x}')
print(f'{x}  {x}  {x}')
print(f'{x}  {x}  {x}')
print(f'{x}{x}{x}{x}{x}{x}{x}')
print(f'{x}  {x}  {x}')
print(f'{x}  {x}  {x}')
print(f'{x}{x}{x}{x}{x}{x}{x}')